/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  referenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
  cliSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cli',
    },
  ],
};

module.exports = sidebars;
