# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Site

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/deploy.yml
      - docs/**
      - src/**
      - static/**
      - "*.js"
      - "*.ts"
      - "*.json"
      - "*.lock"
  pull_request:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/deploy.yml
      - docs/**
      - src/**
      - static/**
      - "*.js"
      - "*.ts"
      - "*.json"
      - "*.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-check:
    uses: recyclarr/recyclarr/.github/workflows/reusable-precheck.yml@0437b89fad4dfc45024920cba4a0f7cb42af9916 # master

  build:
    name: Build
    needs: pre-check
    if: needs.pre-check.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: site-build
          path: build
          retention-days: 1
