# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Cleanup Deployments

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old deployments
        uses: Th3S4mur41/cleanup-cloudflare-deployments@ed1f68249cb7bc0f0e23f6f083008594596d5f01 # main
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: recyclarr-wiki
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cleanup-types: all
          preview-keep: 2
          production-keep: 5
