# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Markdown Lint

on:
  push:
    paths:
      - "**.md"
      - .github/workflows/markdown-lint.yml
      - .markdownlint.yml
  pull_request:
    paths:
      - "**.md"
      - .github/workflows/markdown-lint.yml
      - .markdownlint.yml

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: |
            **.md
